name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Generate manifest.json
        run: |
          PDF_DIR="public/pdfs"
          mkdir -p "$PDF_DIR"
          echo "[]" > /tmp/items.json
          find "$PDF_DIR" -name "*.pdf" -o -name "*.PDF" | while IFS= read -r f; do
            name=$(basename "$f")
            size=$(stat -c %s "$f" 2>/dev/null || echo 0)
            jq --arg file "$name" --argjson size "$size" '. + [{file:$file, size:$size}]' /tmp/items.json > /tmp/items_new.json
            mv /tmp/items_new.json /tmp/items.json
          done
          echo "{\"items\":$(cat /tmp/items.json)}" > "$PDF_DIR/manifest.json"
          echo "Contenido de public:"
          ls -la public/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
